# Generated by Django 4.2.6 on 2023-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
